// ============================================================================
// Rust WASM Loader and Benchmark Wrapper
// ============================================================================
// This module handles loading and calling Rust WASM functions.
// If Rust WASM is not built/available, it gracefully falls back.
// ============================================================================

let rustWasm: Record<string, (...args: unknown[]) => unknown> | null = null;
let isRustLoaded = false;
let rustLoadError: string | null = null;

// Initialize Rust WASM module
export async function initRustWasm(): Promise<boolean> {
  if (isRustLoaded) return true;
  
  try {
    // Try to fetch the Rust WASM files to check if they exist
    const wasmResponse = await fetch('/wasm/rust_benchmarks.wasm');
    if (!wasmResponse.ok) {
      throw new Error('Rust WASM not found');
    }

    // Dynamic import of the init module (generated by wasm-pack)
    // Using indirect import to bypass TypeScript module resolution
    const initPath = '/wasm/rust_wasm_init.js';
    const initModule = await Function('return import("' + initPath + '")')();
    await initModule.default('/wasm/rust_benchmarks.wasm');
    rustWasm = initModule;
    isRustLoaded = true;
    console.log('🦀 Rust WASM initialized successfully');
    return true;
  } catch (err: unknown) {
    // Rust WASM not available - this is expected if not built yet
    const message = err instanceof Error ? err.message : 'Unknown error';
    rustLoadError = 'Rust WASM not built. Run: cd rust-wasm && ./build.sh';
    console.warn('⚠️ Rust WASM not available:', message);
    console.info('ℹ️ To enable Rust benchmarks, install Rust and run: cd rust-wasm && ./build.sh');
    return false;
  }
}

export function isRustWasmLoaded(): boolean {
  return isRustLoaded;
}

export function getRustLoadError(): string | null {
  return rustLoadError;
}

// ============================================================================
// Rust Benchmark Functions - matching Go/JS interface
// Returns undefined if Rust is not available
// ============================================================================

const createBenchmarkFn = (fnName: string) => () => {
  if (!isRustLoaded || !rustWasm) return undefined;
  try {
    const fn = rustWasm[fnName];
    if (typeof fn === 'function') {
      return fn();
    }
    return undefined;
  } catch (e) {
    console.error(`Rust ${fnName} error:`, e);
    return undefined;
  }
};

export const rustBenchmarks = {
  // Math & CPU
  matrixMultiply: createBenchmarkFn('rust_matrix_multiply'),
  primeSieve: createBenchmarkFn('rust_prime_sieve'),
  fibonacci: createBenchmarkFn('rust_fibonacci'),
  monteCarloPi: createBenchmarkFn('rust_monte_carlo_pi'),
  nBody: createBenchmarkFn('rust_n_body'),
  mandelbrot: createBenchmarkFn('rust_mandelbrot'),

  // Crypto
  sha256: createBenchmarkFn('rust_sha256'),
  aesEncrypt: createBenchmarkFn('rust_aes_encrypt'),

  // Memory & Data
  jsonParse: createBenchmarkFn('rust_json_parse'),
  quickSort: createBenchmarkFn('rust_quicksort'),
  bubbleSort: createBenchmarkFn('rust_bubblesort'),

  // Graphics
  rayTrace: createBenchmarkFn('rust_ray_trace'),

  // System
  zipCompression: createBenchmarkFn('rust_compression')
};
